services:
  - type: web
    name: campusfix
    runtime: docker
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "10000"
      - key: APP_BASE_URL
        value: "/"
      - key: DB_SSL
        value: "true"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
